Module7 task2
htmlacademy-javascript/803375-keksobooking-23 pull request #7
Opened 2021-06-26 12:13 UTC by Kshatria

2021-06-30 08:42 UTC, VanessaGrapefruit commented on js/popupOffer.js
>    .querySelector('.popup')
Вот это лучше делать внутри функции createPopupOffer, так как ты клонируешь эту штуку один раз, и потом просто перезаписываешь все поля. Могут появиться баги

2021-06-30 08:52 UTC, VanessaGrapefruit requested changes

2021-06-30 08:52 UTC, VanessaGrapefruit commented on js/popupOffer.js
>    .querySelector('.popup')
В каждую функцию, которая рендерит какое-то поле (createTitle, createAdress), передавай переменную card, чтобы абстрагироваться от внешний переменных и работать только с собственными аргументами

2021-06-30 08:52 UTC, VanessaGrapefruit commented on js/popupOffer.js
> +const offers = createOffers()
А вот это лучше делать внутри createAllOffers

2021-06-30 08:52 UTC, VanessaGrapefruit commented on js/popupOffer.js
> +}
Вообще говоря, у меня есть сомнения в необходимости этой функции. Очень сомневаюсь, что она пригодится в будущем, так как скорее всего ты будешь рендерить только один оффер в форме

2021-06-30 08:52 UTC, VanessaGrapefruit commented on js/popupOffer.js
> +}
И еще проверь, работает ли эта функция без cloneNode. Если работает без нее, то убирай. А то наклонируешь кучу элементов, а потом не будешь понимать, откуда берутся багию

2021-07-03 13:08 UTC, Kshatria commented on js/popupOffer.js
>    .querySelector('.popup')
+

2021-07-03 13:09 UTC, Kshatria commented on js/popupOffer.js
> +const offers = createOffers()
+

2021-07-03 13:09 UTC, Kshatria commented on js/popupOffer.js
> +}
+

2021-07-07 17:02 UTC, closed without merging