Module8 task1
htmlacademy-javascript/803375-keksobooking-23 pull request #8
Opened 2021-06-27 11:56 UTC by Kshatria

2021-06-30 09:02 UTC, VanessaGrapefruit requested changes

2021-06-30 09:02 UTC, VanessaGrapefruit commented on js/formValidate.js
> +validateCapacityRooms();
зачем?

2021-07-03 16:02 UTC, Kshatria commented on js/formValidate.js
> +validateCapacityRooms();
что бы он сразу проверил количество комнат по умолчанию при загрузке страницы и заблокировал лишние варианты на количество гостей.

2021-07-03 16:02 UTC, Kshatria commented on js/formValidate.js
> +  capacity = document.querySelector('#capacity');
+

2021-07-04 17:35 UTC, merged